
# UI ---------------------------------------------------------------------------
page_ui_overview <- 
  page_fluid(uiOutput("value_box_row_overview_01"),
             navset_card_tab(full_screen = TRUE,
                             title = "Charts",
                             height = 900,
                             nav_panel(title = "Points",
                                       plotlyOutput("chart_overview_points")),
                             nav_panel(title = "Points per game",
                                       plotlyOutput("chart_overview_points_per_game")),
                             nav_panel(title = "Payment",
                                       plotlyOutput("chart_overview_payment")),
                             nav_panel(title = "Soli",
                                       plotlyOutput("chart_overview_soli")),
                             nav_panel(title = "Games",
                                       plotlyOutput("chart_overview_games_played")),
                             nav_panel(title = "Victories: Match",
                                       plotlyOutput("chart_overview_victories_match")),
                             nav_panel(title = "Victories: Matchday",
                                       plotlyOutput("chart_overview_victories_matchday")),
                             nav_panel(title = "Position",
                                       plotlyOutput("chart_overview_position"))
                             ),
             uiOutput("value_box_row_overview_02"),
             uiOutput("value_box_row_overview_03"),
             uiOutput("value_box_row_overview_04"),
             navset_card_tab(full_screen = TRUE,
                             title = "Raw Data",
                             height = 900,
                             nav_panel(title = "All",
                                       reactableOutput("reacttable_overview_match_all")),
                             nav_panel(title = "Match selection",
                                       reactableOutput("reacttable_overview_match_selection")),
                             nav_panel(title = "Matchday selection",
                                       reactableOutput("reacttable_overview_matchday_selection")),
                             nav_panel(title = "Match summary",
                                       reactableOutput("reacttable_overview_match_summary")),
                             nav_panel(title = "Player summary",
                                       reactableOutput("reacttable_overview_player_summary")),
                             nav_panel(title = "Key values",
                                       reactableOutput("reacttable_overview_key_values")),
                             nav_panel(title = "Pictures",
                                       reactableOutput("reacttable_pictures_all"))
                             )
             ) 
               