

tabItem_page_overview <-
tabItem("page_overview",
        fluidRow(infoBoxOutput(outputId ="infobox_overview_spieltage",width = 3),
                 infoBoxOutput(outputId ="infobox_overview_einzahlung", width = 3),
                 infoBoxOutput(outputId ="infobox_overview_spieltag_letzter", width = 3),
                 infoBoxOutput(outputId ="infobox_overview_meisten_punkte", width = 3)),
        fluidRow(tabBox(width = 12,
                        #title = "First tabBox",
                        height = 550,
                        id = "tabset1",
                        tabPanel("Punkte",
                                 plotlyOutput("chart_punkte",
                                              height = 500, 
                                              width = 'auto')),
                        tabPanel("Einzahlungen",
                                 plotlyOutput("chart_einhalungen",
                                              height = 500,
                                              width = 'auto')),
                        tabPanel("Durchschnittliche Punkte pro Spiel",
                                 plotlyOutput("chart_punkte_pro_spiel",
                                              height = 500,
                                              width = 'auto')),
                        tabPanel("Anzahl der Spiele",
                                 plotlyOutput("chart_anzahl_spiele",
                                              height = 500,
                                              width = 'auto')),
                        tabPanel("Anzahl der Spieltagssiege",
                                 plotlyOutput("chart_spieltagssiege",
                                              height = 500,
                                              width = 'auto')),
                        tabPanel("Anzahl der Soli",
                                 plotlyOutput("chart_anzahl_soli",
                                              height = 500,
                                              width = 'auto'))
        )))
